"""Public Auth feature entry points."""

from .Tools.database import AuthDatabase
from .Tools.models import (
    ACCESS_TOKEN_EXPIRE_MINUTES,
    JWT_ALGORITHM,
    JWT_SECRET_KEY,
    REFRESH_TOKEN_EXPIRE_DAYS,
    create_access_token,
    create_refresh_token,
    decode_token,
    extract_user_id,
)
from .Tools.routes import auth_db, get_current_user, router
from .Tools.schemas import (
    ApiKeyCreate,
    ApiKeyResponse,
    ChatAssistantMessageCreate,
    ChatMessageResponse,
    ChatThreadCreate,
    ChatThreadDetailResponse,
    ChatThreadResponse,
    ChatTurnCreate,
    ChatUserMessageCreate,
    SubscriptionResponse,
    Token,
    TokenPayload,
    UploadedDocumentResponse,
    UserCreate,
    UserResponse,
    UserUpdate,
)
from .Tools.tables import (
    DB_URL,
    DEFAULT_AUTH_DB_PATH,
    api_keys,
    chat_messages,
    chat_threads,
    metadata,
    refresh_tokens,
    subscriptions,
    uploaded_documents,
    users,
)

auth_router = router

__all__ = [
    "ACCESS_TOKEN_EXPIRE_MINUTES",
    "ApiKeyCreate",
    "ApiKeyResponse",
    "AuthDatabase",
    "ChatAssistantMessageCreate",
    "ChatMessageResponse",
    "ChatThreadCreate",
    "ChatThreadDetailResponse",
    "ChatThreadResponse",
    "ChatTurnCreate",
    "ChatUserMessageCreate",
    "DB_URL",
    "DEFAULT_AUTH_DB_PATH",
    "JWT_ALGORITHM",
    "JWT_SECRET_KEY",
    "REFRESH_TOKEN_EXPIRE_DAYS",
    "SubscriptionResponse",
    "Token",
    "TokenPayload",
    "UploadedDocumentResponse",
    "UserCreate",
    "UserResponse",
    "UserUpdate",
    "api_keys",
    "auth_db",
    "auth_router",
    "chat_messages",
    "chat_threads",
    "create_access_token",
    "create_refresh_token",
    "decode_token",
    "extract_user_id",
    "get_current_user",
    "metadata",
    "refresh_tokens",
    "router",
    "subscriptions",
    "uploaded_documents",
    "users",
]
